<a href="https://colab.research.google.com/github/Murad-pitafi/Data_science/blob/main/Murad_GDSC_DS_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <font color=orange><b>GDSC DATA SCIENCE </b></font>

## Numpy and Pandas Assignment

### <font color=red>Numpy Tasks</font>

In [ ]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.22.4


### Create a numpy array of size 10, filled with zeros.

In [ ]:
# your code goes here
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Create a numpy matrix of 2*2 integers, filled with ones.

In [ ]:
# your code goes here
arr = np.ones((2,2), dtype=int)
print(arr)

[[1 1]
 [1 1]]


### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [ ]:
# your code goes here
arr = np.array([[1,3,5],[5,3,7]])
ones_like = np.ones_like(arr)
print(ones_like)

[[1 1 1]
 [1 1 1]]


### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [ ]:
# your code goes here

matrx = np.matrix([[1, 2], [3, 4]])
zeros_matrix = np.zeros_like(matrx)

print(zeros_matrix)


[[0 0]
 [0 0]]


### Create a numpy matrix of 4*4 integers, filled with fives.

In [ ]:
# your code goes here
mtrx = np.matrix(np.ones((4,4), dtype=int)*5)
print(mtrx)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [ ]:
# your code goes here

zero_8 = np.arange(9)
mat = np.reshape(zero_8, (3,3))
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Create an array from 1 to 10 and return the index of the numbers greater than 5.

In [ ]:
# your code goes here
one_ten = np.arange(1,11)
print(np.where(one_ten > 5))


(array([5, 6, 7, 8, 9]),)


## How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
# your code goes here
float32 = np.array([3.4,5.2,5.3], dtype = np.float32)
int32 = float32.view(dtype=np.int32)
#print(int32)
int32+=1 #in place
print(int32)


[1079613851 1084647015 1084856731]


##  How to swap two rows of an array?

In [ ]:
# your code goes here
arr=np.arange(1,10)
mat = np.reshape(arr, (3,3))
print('original')
print(mat)
mat[[0, 1], :] = mat[[1, 0], :]
print("after swapping")
print(mat)

original
[[1 2 3]
 [4 5 6]
 [7 8 9]]
after swapping
[[4 5 6]
 [1 2 3]
 [7 8 9]]


## Create a 3x3 matrix and compute it's rank?

In [ ]:
# your code goes here
rank = np.linalg.matrix_rank(np.array([[1,3],[4,5]])) # done by using linear Algebra module of numpy
print(rank)

2


## Create two points and calculate the Euclidean distance between them using NumPy?

In [ ]:
# your code goes here
point1 = np.arange(1,4)
point2 = np.arange(4,7)
Euclidean_dist= np.linalg.norm(point1-point2)
print("Euclidean distance is = ", Euclidean_dist)


Euclidean distance is =  5.196152422706632


## Create a Matrix(3,3) of random values from a Gaussian distribution?

In [ ]:
# your code goes here
mat = np.random.normal(size=(3,3)) # Gaussian Distribution or Normal Distribution
print(mat)

[[ 0.0879304   0.26099284  0.72048763]
 [ 0.608161   -1.01191277  1.6975242 ]
 [ 0.91098934  0.54070783  0.42314702]]


### <font color=red>Pandas Tasks (Basic) </font>

## Create a sample dataframe and swap two rows using pandas?

In [ ]:
# your code goes here
import pandas as pd
df = pd.DataFrame({'c1':[1,3,4], 'c2':[4,5,3]})
print(df) 
df.iloc[[0,2]] = df.iloc[[2,0]]
print("after swaping")
print(df)

   c1  c2
0   1   4
1   3   5
2   4   3
after swaping
   c1  c2
0   4   3
1   3   5
2   1   4


## Create 5 pandas series of integers and combine them to form pandas dataframe object?

In [ ]:
# your code goes here

s1 = pd.Series(np.random.randint(0,10, size = 3))
s2 = pd.Series(np.random.randint(0,10, size = 3))
s3 = pd.Series(np.random.randint(0,10, size = 3))
s4 = pd.Series(np.random.randint(0,10, size = 3))
s5 = pd.Series(np.random.randint(0,10, size = 3))
df = pd.concat([s1,s2,s3,s4,s5], axis=1)
print(df)  

   0  1  2  3  4
0  9  4  5  6  8
1  6  4  5  3  0
2  3  6  7  3  6


## Create two sample series and stack them vertically and horizontally?

In [ ]:
# your code goes here
vertical_stack = pd.concat([s1,s2], axis=1) # axis 1 means whenever data will be entered it will be in columns, alternatively vertical
horizontal_stack = pd.concat([s1,s2], axis=0) #axis 0 means whenever data will be entered it will be in rows, alternatively Horizontanlly
print("veritcal stack ")
print(vertical_stack)
print("Horizontal stack")
print(horizontal_stack)

veritcal stack 
   0  1
0  9  4
1  6  4
2  3  6
Horizontal stack
0    9
1    6
2    3
0    4
1    4
2    6
dtype: int64


## Return the items of series A not present in series B?

In [ ]:
# your code goes here
sA = pd.Series(np.arange(1,6))
sB = pd.Series(np.arange(3,8))
mask = ~sA.isin(sB)
result = sA[mask]
print(result)

0    1
1    2
dtype: int64


## Create a sample dataframe and change the order of columns? 

In [ ]:
# your code goes here
df = pd.DataFrame({'c1': [1, 2,5], 'c2': [7, 4, 3], 'c3': [7, 7, 1]})
print('Original')
print(df)

df = df[['c2', 'c3', 'c1']] # there can be multiple ways of changing order of column but here i have used technique of subseting columns

print("after changing the column order")
print(df)


Original
   c1  c2  c3
0   1   7   7
1   2   4   7
2   5   3   1
after changing the column order
   c2  c3  c1
0   7   7   1
1   4   7   2
2   3   1   5
